Lesson3
tyrrannt/django pull request #2
Opened 2020-12-09 05:26 UTC by tyrrannt

2020-12-09 13:22 UTC, Vokler requested changes

2020-12-09 13:22 UTC, Vokler commented on mainapp/admin.py
> +from .models import ProductCategory, Product
Рекомендую использовать (вернее не я, а pep8) абсолютный импорт, то есть from mainapp.models
https://www.python.org/dev/peps/pep-0008/#id23

2020-12-09 13:22 UTC, Vokler commented on mainapp/models.py
> +    uid = models.AutoField(primary_key=True)
Не совсем понял, зачем вы добавили данное поле? Ведь id генерируется автоматически для всех моделей

2020-12-09 13:22 UTC, Vokler commented on mainapp/models.py
> +    uid = models.AutoField(primary_key=True)
То же самое

2020-12-09 13:22 UTC, Vokler commented on mainapp/models.py
> +        return f"{self.name} ({self.category.name})"
Соблюдайте везде одинаковый стиль кавычек

2020-12-09 13:22 UTC, Vokler commented on mainapp/views.py
> +from .models import ProductCategory, Product
То же самое, что писал выше насчет абсолютного импорта

2020-12-09 15:00 UTC, tyrrannt commented on mainapp/models.py
> +    uid = models.AutoField(primary_key=True)
Учту на будущее, привычка при создании бд определять все поля

2020-12-09 15:00 UTC, tyrrannt commented on mainapp/models.py
> +    uid = models.AutoField(primary_key=True)
Учту на будущее, привычка при создании бд определять все поля

2020-12-10 09:12 UTC, Vokler approved these changes

2020-12-10 09:13 UTC, merged